#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-TCP
Version  : 2.19
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-TCP-2.19.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-TCP-2.19.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtest-tcp-perl/libtest-tcp-perl_2.19-1.debian.tar.xz
Summary  : 'testing TCP program'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Test-TCP-man
BuildRequires : perl(Test::SharedFork)

%description
# NAME
Test::TCP - testing TCP program
# SYNOPSIS
use Test::TCP;
my $server = Test::TCP->new(
listen => 1,
code => sub {
my $socket = shift;
...
},
);
my $client = MyClient->new(host => '127.0.0.1', port => $server->port);
undef $server; # kill child process on DESTROY

%package man
Summary: man components for the perl-Test-TCP package.
Group: Default

%description man
man components for the perl-Test-TCP package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Test-TCP-2.19
mkdir -p %{_topdir}/BUILD/Test-TCP-2.19/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Test-TCP-2.19/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Net/EmptyPort.pm
/usr/lib/perl5/site_perl/5.26.1/Test/TCP.pm
/usr/lib/perl5/site_perl/5.26.1/Test/TCP/CheckPort.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Net::EmptyPort.3
/usr/share/man/man3/Test::TCP.3
/usr/share/man/man3/Test::TCP::CheckPort.3
